name: Deploy to Preview Channel

on:
  pull_request:
    # Optionally configure to run only for specific files. For example:
    # paths:
    # - "website/**"

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
    - name: Install Dependencies
      run: npm install
    - name: Build
      run: npm run build --if-present
      env:
        CI: false
    - uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: "${{ secrets.GITHUB_TOKEN }}"
        firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_AFTER_SCHOOL_59829 }}"
        expires: 30d
        projectId: after-school-59829
